# Directory: pico/
# Modified: 2026-04-08
# Description: Runtime credentials and hardware config for the Pico W. Generated by scripts/generate_pico_config.sh.
# Uses: none
# Used by: pico/main.py

# Generated by scripts/generate_pico_config.sh
WIFI_SSID = ""
WIFI_PASSWORD = ""
MQTT_BROKER = ""
MQTT_PORT = 1883
PIXEL_PIN = 16
PIXEL_COUNT = 255
VERBOSE = True
