#!/usr/bin/env bash
# Directory: scripts/
# Modified: 2026-04-08
# Description: Interactive script that generates pico/device_config.py with WiFi, MQTT broker, and pixel pin values.
# Uses: pico/device_config.py (output target)
# Used by: none (run manually before flashing the Pico W)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/pico/device_config.py"

detected_ssid=""
if command -v iwgetid >/dev/null 2>&1; then
  detected_ssid="$(iwgetid -r || true)"
fi

detected_broker="$(hostname -I | awk '{print $1}')"

default_ssid="${detected_ssid:-YOUR_WIFI}"
default_broker="${detected_broker:-192.168.1.10}"

echo "Generating Pico config at $OUT_FILE"
read -r -p "WiFi SSID [$default_ssid]: " wifi_ssid
wifi_ssid="${wifi_ssid:-$default_ssid}"

read -r -s -p "WiFi password: " wifi_password
echo

read -r -p "MQTT broker IP [$default_broker]: " mqtt_broker
mqtt_broker="${mqtt_broker:-$default_broker}"

read -r -p "Pixel pin (GPIO) [0]: " pixel_pin
pixel_pin="${pixel_pin:-0}"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/generate_pico_config.sh
WIFI_SSID = "$wifi_ssid"
WIFI_PASSWORD = "$wifi_password"
MQTT_BROKER = "$mqtt_broker"
MQTT_PORT = 1883
PIXEL_PIN = $pixel_pin
PIXEL_COUNT = 255
EOF

echo "Generated $OUT_FILE"
